CREATE DATABASE MojeKino;
CREATE TABLE FILMY( 
    ID bigint AUTO_INCREMENT PRIMARY KEY NOT NULL, 
    TYTUL varchar(255) NOT NULL, 
    REZYSER varchar(255) NOT NULL, 
    CZAS_TRWANIA int NOT NULL); 


CREATE TABLE SALE(
    ID bigint AUTO_INCREMENT PRIMARY KEY NOT NULL,
    ILOSC_MIEJSC int NOT NULL
    );


CREATE TABLE SEANSE(
    ID bigint AUTO_INCREMENT PRIMARY KEY NOT NULL,
    TERMIN datetime NOT NULL,
    SALA_ID bigint NOT NULL,
    FILM_ID bigint NOT NULL,
    LICZBA_WOLNYCH_MIEJSC int NOT NULL,
    
    CONSTRAINT `sala_fk` FOREIGN KEY (`SALA_ID`) 
    REFERENCES SALE(`ID`),
    
    CONSTRAINT `film_fk` FOREIGN KEY (`FILM_ID`) 
    REFERENCES FILMY(`ID`)
);


CREATE TABLE KLIENCI(
    ID bigint AUTO_INCREMENT PRIMARY KEY NOT NULL,
    IMIE varchar(255) NOT NULL,
    NAZWISKO varchar(255) NOT NULL,
    MAIL varchar(255) NOT NULL
    );


CREATE TABLE SPRZEDAWCY(
    ID bigint AUTO_INCREMENT PRIMARY KEY NOT NULL,
    IMIE varchar(255) NOT NULL,
    NAZWISKO varchar(255) NOT NULL
    );


CREATE TABLE BILETY(
    ID bigint AUTO_INCREMENT PRIMARY KEY NOT NULL,
    SEANS_ID bigint NOT NULL,
    SPRZEDAWCA_ID bigint NOT NULL,
    KLIENT_ID bigint NOT NULL,
    CENA int NOT NULL, 
    
    CONSTRAINT `seans_fk` FOREIGN KEY (`SEANS_ID`) 
    REFERENCES  SEANSE(`ID`),

    CONSTRAINT `sprzedawca_fk` FOREIGN KEY (`SPRZEDAWCA_ID`)
    REFERENCES  SPRZEDAWCY(`ID`),

    CONSTRAINT `klient_fk` FOREIGN KEY (`KLIENT_ID`)
    REFERENCES  KLIENCI(`ID`)
);

CREATE TABLE FILMY_RODZAJ(
    ID bigint AUTO_INCREMENT PRIMARY KEY NOT NULL,
    FILM_ID  bigint NOT NULL,
    RODZAJ_FILMU_ID bigint NOT NULL,

    CONSTRAINT `filmy_fk` FOREIGN KEY (`FILM_ID`)
    REFERENCES FILMY(`ID`),

    CONSTRAINT `rodzaj_fk` FOREIGN KEY (`RODZAJ_FILMU_ID`)
    REFERENCES RODZAJ_FILMU(`ID`)
);

CREATE TABLE RODZAJ_FILMU(
    ID bigint AUTO_INCREMENT PRIMARY KEY NOT NULL,
    NAZWA varchar(255) NOT NULL
);

INSERT INTO `SPRZEDAWCY` (`IMIE`,`NAZWISKO`) VALUES
("KACPER","ROBAKOWSKI"),
("MARCIN","LEJK"),
("AUGUST","CZARNY"),
("NIKODEM","MALY"),
("RAFAL","TRZASKOWSKI");

INSERT INTO `RODZAJ_FILMU` (`NAZWA`) VALUES
("Dramat"),
("Komedia"),
("Thriller"),
("Akcji"),
("Romantyczny");

INSERT INTO `SALE` (`ILOSC_MIEJSC`) VALUES
(50),
(75),
(100),
(144),
(144);

INSERT INTO `KLIENCI` (`IMIE`,`NAZWISKO`,`MAIL`) VALUES
("Kacper", "Malinowski", "malinakapi2006@gmail.com"),
("Nikodem", "Czerwiński", "jamal366@gmail.com"),
("Piotr", "Detkiewicz", "grzbynokoks@gmail.com"),
("Mariusz", "Nalepa", "nalepa1985@gmail.com"),
("Piotr", "Kasztanowski", "Piter@gmail.com");

INSERT INTO `FILMY` (`TYTUL`,`REZYSER`,`CZAS_TRWANIA`) VALUES
("Tuż po zmroku", "Benjamin Brewer", 82),
("Rytułał śmierci", "George Gallo", 92),
("Uległość", "S.K. Dale", 95),
("Ona słucha", "Chris Weitz", 123),
("After 5. Na zawsze", "Castille Landon", 95);

INSERT INTO `SEANSE` (`TERMIN`, `SALA_ID`, `FILM_ID`, `LICZBA_WOLNYCH_MIEJSC`) VALUES
("2024-11-27 16:30:00", 5, 2, 75),
("2024-11-31 23:30:00", 1, 3, 50),
("2024-12-25 15:15:00", 2, 1, 100),
("2024-12-27 16:15:00", 3, 5, 144),
("2025-01-2 20:45:00", 3, 4, 144);

INSERT INTO `FILMY_RODZAJ` (`FILM_ID`, `RODZAJ_FILMU_ID`) VALUES
(2, 2),
(3, 3),
(1, 1),
(4, 4),
(5, 5);

INSERT INTO `BILETY` (`SEANS_ID`, `SPRZEDAWCA_ID`, `KLIENT_ID`, `CENA`) VALUES
(2, 3, 3, 29.99),
(4, 2, 4, 19.99),
(1, 4, 2, 14.99),
(3, 1, 5, 14.99),
(5, 5, 1, 24.99);


SELECT 
    BILETY.ID AS BILET_ID, 
    KLIENCI.IMIE AS IMIE_KLIENTA, 
    KLIENCI.NAZWISKO AS NAZWISKO_KLIENTA, 
    FILMY.TYTUL AS TYTUL_FILMU, 
    BILETY.CENA AS CENA_BILETU
FROM 
    BILETY
INNER JOIN 
    KLIENCI ON BILETY.KLIENT_ID = KLIENCI.ID
INNER JOIN 
    SEANSE ON BILETY.SEANS_ID = SEANSE.ID
INNER JOIN 
    FILMY ON SEANSE.FILM_ID = FILMY.ID
ORDER BY 
    BILETY.CENA ASC;


SELECT 
    SEANSE.ID AS SEANS_ID, 
    SEANSE.TERMIN AS DATA_I_CZAS, 
    SALE.ID AS SALA_ID, 
    SALE.ILOSC_MIEJSC AS MIEJSCA_W_SALI, 
    FILMY.TYTUL AS TYTUL_FILMU
FROM 
    SEANSE
INNER JOIN 
    SALE ON SEANSE.SALA_ID = SALE.ID
INNER JOIN 
    FILMY ON SEANSE.FILM_ID = FILMY.ID
ORDER BY 
    SEANSE.TERMIN DESC;


SELECT 
    SPRZEDAWCY.IMIE AS IMIE_SPRZEDAWCY, 
    SPRZEDAWCY.NAZWISKO AS NAZWISKO_SPRZEDAWCY, 
    KLIENCI.IMIE AS IMIE_KLIENTA, 
    KLIENCI.NAZWISKO AS NAZWISKO_KLIENTA, 
    BILETY.CENA AS CENA_BILETU
FROM 
    BILETY
INNER JOIN 
    SPRZEDAWCY ON BILETY.SPRZEDAWCA_ID = SPRZEDAWCY.ID
INNER JOIN 
    KLIENCI ON BILETY.KLIENT_ID = KLIENCI.ID
ORDER BY 
    SPRZEDAWCY.NAZWISKO ASC;
